CREATE TABLE TB_VARIACAO_DAILY(

           ID INT IDENTITY(1,1) PRIMARY KEY
           ,CL_DATE DATETIME
           ,CL_VALUE DOUBLE PRECISION
           ,CL_VARIATION_PREVIOUS_DATE DOUBLE PRECISION
           ,CL_VARIATION_FIRST_DATE DOUBLE PRECISION		   
);